---
- name: geerlingguy.docker
  version: 2.7.0

- name: bertvv.samba
  version: v2.7.0

- name: geerlingguy.nfs
  version: 1.5.0

- name: githubixx.ansible_role_wireguard
  version: 6.0.2

- name: softasap.sa-vpn-softether
  version: 1.3.0