- name: Autoheal Docker Container
  docker_container:
    name: autoheal
    image: willfarrell/autoheal
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      AUTOHEAL_CONTAINER_LABEL: "autoheal.enable"
    restart_policy: always
    memory: 512m
