---
- name: Create Bazarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bazarr_data_directory }}"

- name: Bazarr
  docker_container:
    name: bazarr
    image: linuxserver/bazarr
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ bazarr_tv_directory }}:/tv:rw"
      - "{{ bazarr_movies_directory }}:/movies:rw"
      - "{{ bazarr_data_directory }}:/config:rw"
    ports:
      - "{{ bazarr_port }}:6767"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ bazarr_user_id }}"
      PGID: "{{ bazarr_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ bazarr_available_externally }}"
      traefik.http.services.bazarr-svc.loadbalancer.server.port: "6767"
      traefik.http.routers.bazarr.middlewares: "{% if ldap_enabled|default(false)|bool %}auth-sso{% endif %}"
      traefik.http.routers.bazarr.rule: "Host(`bazarr.{{ ansible_nas_domain }}`)"
      traefik.http.routers.bazarr.tls: "true"