- name: Create Bitwarden Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bitwarden_data_directory }}"

- name: Bitwarden Docker Container
  docker_container:
    name: bitwarden
    image: bitwardenrs/server:latest
    purge_networks: true
    networks:
      - name: web
    pull: true
    ports:
      - "{{ bitwarden_port_a }}:80"
      - "{{ bitwarden_port_b }}:3012"
    volumes:
      - "{{ bitwarden_data_directory }}:/data:rw"
    env:
      SIGNUPS_ALLOWED: "{{ bitwarden_allow_signups }}"
      ADMIN_TOKEN: "{{ bitwarden_admin_token }}"
      LOG_FILE: "/data/bitwarden.log"
      WEBSOCKET_ENABLED: "true"
    labels:
      autoheal.enable: "true"

      traefik.enable: "{{ bitwarden_available_externally }}"

      traefik.http.services.bitwarden-web-svc.loadbalancer.server.port: "80"
      traefik.http.routers.bitwarden-web.rule: "Host(`bitwarden.{{ ansible_nas_domain }}`)"
      traefik.http.routers.bitwarden-web.tls: "true"
      traefik.http.routers.bitwarden-web.service: bitwarden-web-svc

      traefik.http.services.bitwarden-ws-svc.loadbalancer.server.port: "3012"
      traefik.http.routers.bitwarden-ws.rule: "Host(`bitwarden.{{ ansible_nas_domain }}`) && Path(`/notifications/hub`)"
      traefik.http.routers.bitwarden-ws.tls: "true"
      traefik.http.routers.bitwarden-ws.middlewares: bitwarden-ws-strip
      traefik.http.routers.bitwarden-ws.service: bitwarden-ws-svc
      traefik.http.middlewares.bitwarden-ws-strip.stripprefix.prefixes: /notifications/hub
    restart_policy: always
    #memory: 1g

- name: Bitwarden Backup Container
  docker_container:
    name: bitwarden-backup
    image: bruceforce/bw_backup:latest
    pull: true
    restart_policy: always
    volumes_from: bitwarden
    memory: 1g
