---
- name: Create Couchpotato Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ docker_home }}/couchpotato/config"

- name: Couchpotato Docker Container
  docker_container:
    name: couchpotato
    image: linuxserver/couchpotato
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ couchpotato_config_directory }}:/config:rw"
      - "{{ couchpotato_downloads_directory }}:/downloads:rw"
      - "{{ couchpotato_movies_directory }}:/movies:rw"
      - "{{ couchpotato_torrents_directory }}:/torrents:rw"
    ports:
      - "{{ couchpotato_port }}:5050"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ couchpotato_user_id }}"
      PGID: "{{ couchpotato_group_id }}"
    restart_policy: always
    memory: 1g
    labels:
      traefik.enable: "{{ couchpotato_available_externally }}"
      traefik.http.services.couchpotato-svc.loadbalancer.server.port: "5050"
      traefik.http.routers.couchpotato.middlewares: "{% if ldap_enabled|default(false)|bool %}auth-sso{% endif %}"
      traefik.http.routers.couchpotato.rule: "Host(`couchpotato.{{ ansible_nas_domain }}`)"
      traefik.http.routers.couchpotato.tls: "true"