---
- name: Create Gitea group account
  group:
    name: git
    gid: 1309
    state: present

- name: Create Gitea user account
  user:
    name: git
    uid: 1309
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: git

- name: Create Gitea Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: git
    group: git
    recurse: yes
  with_items:
    - "{{ gitea_data_directory }}/gitea"
    - "{{ gitea_data_directory }}/creds"

- name: Create Gitea user on Postgres
  postgresql_user:
    name: gitea
    password: "{{ lookup('password', creds_direcrory +'/gitea/gitea_postgres_passwd length=32') }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    state: present
    login_host: 127.0.0.1

- name: Create Gitea database on Postgres
  postgresql_db:
    name: gitea
    owner: gitea
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    state: present
    login_host: 127.0.0.1


- name: Create Gitea container
  docker_container:
    name: gitea
    image: gitea/gitea:1.6
    pull: true
    purge_networks: true
    networks:
      - name: postgres
      - name: web
    volumes:
      - "{{ gitea_data_directory }}/gitea:/data:rw"
    ports:
      - "{{ gitea_port_http }}:3000"
      - "{{ gitea_port_ssh }}:22"
    env:
      DB_TYPE: "postgres"
      DB_HOST: "postgres:5432"
      DB_NAME: "gitea"
      DB_USER: "gitea"
      DB_PASSWD: "{{ lookup('password', creds_direcrory +'/gitea/gitea_postgres_passwd length=32') }}"
      RUN_MODE: "prod"
      SSH_DOMAIN: "{{ ansible_nas_hostname }}"
      SSH_PORT: "{{ gitea_port_ssh }}"
      ROOT_URL: "{% if (gitea_available_externally | bool) %}https://gitea.{{ ansible_nas_domain }}/{% else %}http://{{ ansible_nas_hostname }}:{{ gitea_port_http }}/{% endif %}"
      USER_UID: "1309"
      USER_GID: "1309"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ gitea_available_externally }}"
      traefik.http.services.gitea-svc.loadbalancer.server.port: "3000"
      traefik.http.routers.gitea.rule: "Host(`gitea.{{ ansible_nas_domain }}`)"
      traefik.http.routers.gitea.tls: "true"