---
- name: Create Guacamole directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ guacamole_data_directory }}/config"

# docker run -v /home/david/.guac:/config:rw  -p 8080:8080   oznu/guacamole

- name: Guacamole Container
  docker_container:
    name: guacamole
    image: "oznu/guacamole"
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ guacamole_data_directory }}/config:/config:rw"
    ports:
      - "{{ guacamole_port }}:8080"
    restart_policy: unless-stopped
    memory: 1g
    restart: true
    labels:
      traefik.enable: "{{ guacamole_available_externally }}"
      traefik.http.services.guacamole-svc.loadbalancer.server.port: "8080"
      traefik.http.routers.guacamole.rule: "Host(`guacamole.{{ ansible_nas_domain }}`)"
      traefik.http.routers.guacamole.tls: "true"
