---
- name: Create Heimdall group
  group:
    name: heimdall
    gid: 1310
    state: present

- name: Create Heimdall user
  user:
    name: heimdall
    uid: 1310
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: heimdall

- name: Create Heimdall Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: heimdall
    group: heimdall
  with_items:
    - "{{ heimdall_data_directory }}"
    - "{{ heimdall_data_directory }}/nginx/site-confs"

- name: Template Heimdall nginx config
  template:
    src: heimdall/nginx-sso.conf
    dest: "{{ heimdall_data_directory }}/nginx/site-confs/default"

- name: Create Heimdall container
  docker_container:
    name: heimdall
    image: "{{ heimdall_docker_image }}"
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ heimdall_data_directory }}:/config:rw"
    etc_hosts:
      host.docker.internal: "{{ host_docker_internal_ip }}"
    env:
      PUID: "1310"
      PGID: "1310"
      TZ: "{{ ansible_nas_timezone }}"
    ports:
      - "{{ heimdall_port_http }}:80"
      - "{{ heimdall_port_https }}:443"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ heimdall_available_externally }}"
      traefik.http.services.heimdall-svc.loadbalancer.server.port: "80"
      traefik.http.routers.heimdall.rule: "Host(`heimdall.{{ ansible_nas_domain }}`)"
      traefik.http.routers.heimdall.middlewares: "{% if ldap_enabled|default(false)|bool %}auth-sso{% endif %}"
      traefik.http.routers.heimdall.tls: "true"
