- name: Create Home Assistant Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ homeassistant_data_directory }}/config"

- name: Create HomeAssistant user on Postgres
  postgresql_user:
    name: homeassistant
    password: "{{ lookup('password', creds_direcrory +'/homeassistant/homeassistant_postgres_passwd length=32') }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    state: present
    login_host: 127.0.0.1

- name: Create HomeAssistant database on Postgres
  postgresql_db:
    name: homeassistant
    owner: homeassistant
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    state: present
    login_host: 127.0.0.1

- name: Home Assistant Docker Container
  docker_container:
    name: homeassistant
    image: homeassistant/home-assistant
    pull: true
    volumes:
      - "{{ homeassistant_data_directory }}/config:/config:rw"
      - "{{ homeassistant_movies_directory }}:/media/movies:{{ homeassistant_movies_permissions }}"
      - "{{ homeassistant_music_directory }}:/media/music:{{ homeassistant_music_permissions }}"
      - "{{ homeassistant_tv_directory }}:/media/tv:{{ homeassistant_tv_permissions }}"
    network_mode: host
    restart_policy: always
    env:
      TZ: "{{ ansible_nas_timezone }}"
    healthcheck:
      test: "curl --fail http://127.0.0.1:8123/auth/providers"
      interval: 30s
      retries: 6
      start_period: 60s
      timeout: 15s
    labels:
      autoheal.enable: "true"
      traefik.enable: "{{ homeassistant_available_externally }}"
      traefik.docker.network: ""
      traefik.http.services.homeassistant-svc.loadbalancer.server.port: "8123"
      traefik.http.routers.homeassistant.rule: "Host(`hass.{{ ansible_nas_domain }}`)"
      traefik.http.routers.homeassistant.tls: "true"
      com.centurylinklabs.watchtower.enable: "false"
    memory: 1g
