---
- name: Create jackett Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ jackett_data_directory }}"

- name: jackett
  docker_container:
    name: jackett
    image: linuxserver/jackett
    purge_networks: true
    networks:
      - name: web
    volumes:
      - "{{ jackett_data_directory }}:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ jackett_torrents_root }}:/downloads"
    ports:
      - "{{ jackett_port }}:9117"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: always
    labels:
      traefik.enable: "{{ jackett_available_externally }}"
      traefik.http.services.jackett-svc.loadbalancer.server.port: "9117"
      traefik.http.routers.jackett.rule: "Host(`jackett.{{ ansible_nas_domain }}`)"
      traefik.http.routers.jackett.middlewares: "{% if ldap_enabled|default(false)|bool %}auth-sso{% endif %}"
      traefik.http.routers.jackett.tls: "true"
