---
- name: Create lidarr Directory
  file:
    path: "{{ lidarr_data_directory }}"
    state: directory

- name: lidarr
  docker_container:
    name: lidarr
    image: linuxserver/lidarr
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ lidarr_music_directory }}:/music:rw"
      - "{{ lidarr_downloads_directory }}:/downloads:rw"
      - "{{ lidarr_data_directory }}:/config:rw"
    ports:
      - "{{ lidarr_port }}:8686"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ lidarr_user_id }}"
      PGID: "{{ lidarr_group_id }}"
    restart_policy: always
    memory: 1g
    labels:
      traefik.enable: "{{ lidarr_available_externally }}"
      traefik.http.services.lidarr-svc.loadbalancer.server.port: "8686"
      traefik.http.routers.lidarr.rule: "Host(`lidarr.{{ ansible_nas_domain }}`)"
      traefik.http.routers.lidarr.middlewares: "{% if ldap_enabled|default(false)|bool %}auth-sso{% endif %}"
      traefik.http.routers.lidarr.tls: "true"
