- name: minidlna Docker Container
  docker_container:
    name: minidlna
    image: vladgh/minidlna
    pull: true
    volumes:
      - "{{ minidlna_media_movies }}:/movies:rw"
      - "{{ minidlna_media_tv }}:/tv_series:rw"
      - "{{ minidlna_media_music }}:/music:rw"
    ports:
      - "{{ minidlna_port }}:8201"
    env:
      MINIDLNA_FORCE_SORT_CRITERIA: "+upnp:class,+upnp:originalTrackNumber,+dc:title"
      MINIDLNA_MEDIA_DIR1: "V,/movies"
      MINIDLNA_MEDIA_DIR2: "V,/tv_series"
      MINIDLNA_MEDIA_DIR3: "A,/music"
      MINIDLNA_FRIENDLY_NAME: "{{ minidlna_friendly_name }}"
      MINIDLNA_PORT: "8201"
    network_mode: host
    restart_policy: unless-stopped
    memory: 1g
