- name: Create Mosquitto Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ mosquitto_data_directory }}/config"
    - "{{ mosquitto_data_directory }}/data"
    - "{{ mosquitto_data_directory }}/log"

- name: Create Docker Mosquitto network
  docker_network:
    name: mosquitto

- name: Template mosquitto.conf
  copy:
    src: mosquitto/mosquitto.conf
    dest: "{{ mosquitto_data_directory }}/config/mosquitto.conf"
    force: false

- name: Create Mosquitto container
  docker_container:
    name: mosquitto
    image: eclipse-mosquitto:latest
    pull: true
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    networks:
      - name: mosquitto
    volumes:
      - "{{ mosquitto_data_directory }}/config:/mosquitto/config:rw"
      - "{{ mosquitto_data_directory }}/data:/mosquitto/data:rw"
      - "{{ mosquitto_data_directory }}/log:/mosquitto/log:rw"
    ports:
      - "{{ mosquitto_port_a }}:1883"
      - "{{ mosquitto_port_b }}:9001"
    restart_policy: always
    memory: 1g
