---
- name: Create NZBget Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nzbget_data_directory }}"

- name: NZBGet
  docker_container:
    name: nzbget
    image: linuxserver/nzbget
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ nzbget_download_directory }}:/downloads:rw"
      - "{{ nzbget_data_directory }}:/config:rw"
    ports:
      - "{{ nzbget_port }}:6789"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ nzbget_user_id }}"
      PGID: "{{ nzbget_group_id }}"
    restart_policy: always
    memory: 1g
    labels:
      traefik.enable: "{{ nzbget_available_externally }}"
      traefik.http.services.nzbget-svc.loadbalancer.server.port: "6789"
      traefik.http.routers.nzbget.rule: "Host(`nzbget.{{ ansible_nas_domain }}`)"
      traefik.http.routers.nzbget.middlewares: "{% if ldap_enabled|default(false)|bool %}auth-sso{% endif %}"
      traefik.http.routers.nzbget.tls: "true"
