---
- name: Create ombi Directories
  file:
    path: "{{ ombi_config_directory }}"
    state: directory

- name: ombi
  docker_container:
    name: ombi
    image: linuxserver/ombi
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ ombi_config_directory }}:/config:rw"
    ports:
      - "3579:3579"
    etc_hosts:
      host.docker.internal: "{{ host_docker_internal_ip }}"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ ombi_user_id }}"
      PGID: "{{ ombi_group_id }}"
    restart_policy: always
    memory: 1g
    labels:
      traefik.enable: "{{ ombi_available_externally }}"
      traefik.http.services.ombi-svc.loadbalancer.server.port: "3579"
      traefik.http.routers.ombi.rule: "Host(`ombi.{{ ansible_nas_domain }}`)"
      traefik.http.routers.ombi.tls: "true"
