---
- name: openspeedtest
  docker_container:
    name: openspeedtest
    image: openspeedtest/latest
    purge_networks: true
    networks:
      - name: web
    pull: true
    ports:
      - "{{ openspeedtest_port }}:8080"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ openspeedtest_available_externally }}"
      traefik.http.services.openspeedtest-svc.loadbalancer.server.port: "8080"
      traefik.http.routers.openspeedtest.rule: "Host(`speedtest.{{ ansible_nas_domain }}`, `speedtest-1.{{ ansible_nas_domain }}`, `speedtest-2.{{ ansible_nas_domain }}`, `speedtest-3.{{ ansible_nas_domain }}`, `speedtest-4.{{ ansible_nas_domain }}`)"
      traefik.http.routers.openspeedtest.tls: "true"
