
---
- name: Create Organizr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ organizr_data_directory }}"

- name: Ensure LDAP network is present
  docker_network:
    name: ldap

- name: Create Organizr container
  docker_container:
    name: organizr
    image: organizrtools/organizr-v2:latest
    pull: true
    etc_hosts:
      host.docker.internal: "{{ host_docker_internal_ip }}"
    purge_networks: true
    networks:
      - name: web
      - name: ldap
    volumes:
      - "{{ organizr_data_directory }}:/config:rw"
    env:
      PUID: "{{ organizr_user_id }}"
      PGID: "{{ organizr_group_id }}"
      TZ: "{{ ansible_nas_timezone }}"
    ports:
      - "{{ organizr_port_http }}:80"
      - "{{ organizr_port_https }}:443"
    restart_policy: always
    memory: 1g
    labels:
      traefik.enable: "{{ organizr_available_externally }}"
      traefik.http.services.organizr-svc.loadbalancer.server.port: "80"
      traefik.http.routers.organizr.rule: "Host(`organizr.{{ ansible_nas_domain }}`)"
      traefik.http.routers.organizr.middlewares: "{% if ldap_enabled|default(false)|bool %}auth-sso{% endif %}"
      traefik.http.routers.organizr.tls: "true"