---
- name: Create Portainer Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ portainer_data_directory }}"

- name: Ensure LDAP network is present
  docker_network:
    name: ldap

- name: Portainer Docker Container
  docker_container:
    name: portainer
    image: portainer/portainer
    purge_networks: true
    networks:
      - name: web
      - name: ldap
    pull: true
    volumes:
      - "{{ portainer_data_directory }}:/data:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "{{ portainer_port }}:9000"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ portainer_available_externally }}"
      traefik.http.services.portainer-svc.loadbalancer.server.port: "9000"
      traefik.http.routers.portainer.rule: "Host(`portainer.{{ ansible_nas_domain }}`)"
      traefik.http.routers.portainer.tls: "true"
