---
- name: Install Postgres prerequisites
  apt:
    name: ["libpq-dev", "python-psycopg2", "python3-psycopg2"]
    state: latest

- name: Postgres database directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ postgres_data_directory }}/pgdata"
    - "{{ postgres_data_directory }}/creds"

- name: Create Docker Postgres network
  docker_network:
    name: postgres

- name: Postgres Docker Container
  docker_container:
    name: postgres
    image: "{{ postgres_docker_image }}"
    pull: true
    networks:
      - name: postgres
    networks_cli_compatible: false
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ postgres_data_directory }}/pgdata:/var/lib/postgresql/data:rw"
    ports:
      - 5432:5432
    restart_policy: unless-stopped
    memory: 1g
