---
- name: Create pyLoad Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ pyload_config_directory }}"
    - "{{ pyload_download_directory }}"

- name: pyLoad Docker Container
  docker_container:
    name: pyload
    image: writl/pyload
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ pyload_config_directory }}:/opt/pyload/pyload-config:rw"
      - "{{ pyload_download_directory }}:/opt/pyload/Downloads:rw"
    ports:
      - "{{ pyload_port }}:8000"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      UID: "{{ pyload_user_id }}"
      GID: "{{ pyload_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ pyload_available_externally }}"
      traefik.http.services.pyload-svc.loadbalancer.server.port: "8000"
      traefik.http.routers.pyload.rule: "Host(`pyload.{{ ansible_nas_domain }}`)"
      traefik.http.routers.pyload.tls: "true"
