---
- name: Create Radarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ radarr_data_directory }}"

- name: Radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ radarr_movies_directory }}:/movies:rw"
      - "{{ radarr_download_directory }}:/downloads:rw"
      - "{{ radarr_data_directory }}:/config:rw"
    ports:
      - "{{ radarr_port }}:7878"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ radarr_user_id }}"
      PGID: "{{ radarr_group_id }}"
    restart_policy: always
    memory: 1g
    labels:
      traefik.enable: "{{ radarr_available_externally }}"
      traefik.http.services.radarr-svc.loadbalancer.server.port: "7878"
      traefik.http.routers.radarr.rule: "Host(`radarr.{{ ansible_nas_domain }}`)"
      traefik.http.routers.radarr.middlewares: "{% if ldap_enabled|default(false)|bool %}auth-sso{% endif %}"
      traefik.http.routers.radarr.tls: "true"
