---
- name: Remove Old Sickrage Docker Container
  docker_container:
    name: sickrage
    state: absent
    keep_volumes: true

- name: Create Sickchill Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ sickchill_config_directory }}"

- name: Sickchill Docker Container
  docker_container:
    name: sickchill
    image: linuxserver/sickchill
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ sickchill_config_directory }}:/config:rw"
      - "{{ sickchill_downloads_directory }}:/downloads:rw"
      - "{{ sickchill_tv_directory }}:/tv:rw"
    ports:
      - "{{ sickchill_port }}:8081"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ sickchill_user_id }}"
      PGID: "{{ sickchill_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ sickchill_available_externally }}"
      traefik.http.services.sickchill-svc.loadbalancer.server.port: "8081"
      traefik.http.routers.sickchill.rule: "Host(`sickchill.{{ ansible_nas_domain }}`)"
      traefik.http.routers.sickchill.middlewares: "{% if ldap_enabled|default(false)|bool %}auth-sso{% endif %}"
      traefik.http.routers.sickchill.tls: "true"
