---
- name: Create InfluxDB and Telegraf Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ influxdb_data_directory }}"
    - "{{ telegraf_data_directory }}"

- name: Create Grafana Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "472"
    recurse: yes
  with_items:
    - "{{ grafana_data_directory }}"
    - "{{ grafana_data_directory }}/data"
    - "{{ grafana_data_directory }}/data/dashboards/ansible-nas"
    - "{{ grafana_data_directory }}/config/"
    - "{{ grafana_data_directory }}/config/provisioning"
    - "{{ grafana_data_directory }}/config/provisioning/datasources"
    - "{{ grafana_data_directory }}/config/provisioning/dashboards"

- name: Create Docker stats network
  docker_network:
    name: stats

- name: InfluxDB
  docker_container:
    name: influxdb
    image: influxdb
    pull: true
    networks:
      - name: stats
    volumes:
      - "{{ influxdb_data_directory }}:/var/lib/influxdb:rw"
    ports:
      - "{{ grafana_influxdb_port }}:8086"
    restart_policy: unless-stopped
    env:
      INFLUXDB_LOGGING_LEVEL: "error"
    memory: 1g

- name: hddtemp
  docker_container:
    name: hddtemp
    image: drewster727/hddtemp-docker
    pull: true
    networks:
      - name: stats
    privileged: true
    restart_policy: unless-stopped
    env:
      HDDTEMP_ARGS: "-q -d -F /dev/sd*"
      TZ: "{{ ansible_nas_timezone }}"
    memory: 128m

- name: nut-influxdb-exporter
  when: stat_ups_nut_enabled
  docker_container:
    name: nut-influxdb-exporter
    image: maihai/nut-influxdb-exporter
    pull: true
    networks:
      - name: stats
    restart_policy: unless-stopped
    etc_hosts:
      host.docker.internal: "{{ host_docker_internal_ip }}"
    env:
      INFLUXDB_HOST: influxdb
      NUT_HOST: "{{ stat_ups_nut_host }}"
      NUT_PORT: "{{ stat_ups_nut_port | default('3493') }}"
      INFLUXDB_DATABASE: "{{ stat_ups_nut_database_name }}"
      UPS_NAME: "{{ stat_ups_nut_ups_name }}"
      WATTS: "{{ stat_ups_nut_ups_watts | default(omit) }}"
      INTERVAL: "{{ stat_ups_nut_collection_interval }}"
      TZ: "{{ ansible_nas_timezone }}"
    memory: 128m

- name: Template telegraf.conf
  template:
    src: telegraf/telegraf.conf
    dest: "{{ telegraf_data_directory }}/telegraf.conf"

- name: Telegraf
  docker_container:
    name: telegraf
    image: telegraf
    pull: true
    networks:
      - name: stats
    privileged: true
    ipc_mode: host
    volumes:
      - "{{ telegraf_data_directory }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ samba_shares_root }}:/samba_shares:ro"
      - "/:/hostfs:ro"
      - "/etc:/hostfs/etc:ro"
      - "/proc:/hostfs/proc:ro"
      - "/sys:/hostfs/sys:ro"
      - "/var:/hostfs/var:ro"
      - "/run:/hostfs/run:ro"
    env:
      HOST_ETC: "/hostfs/etc"
      HOST_PROC: "/hostfs/proc"
      HOST_SYS: "/hostfs/sys"
      HOST_VAR: "/hostfs/var"
      HOST_RUN: "/hostfs/run"
      HOST_MOUNT_PREFIX: "/hostfs"
    restart_policy: unless-stopped
    memory: 1g

- name: Template Grafana data source
  template:
    src: grafana/provisioning/datasources/ansible-nas.yml
    dest: "{{ grafana_data_directory }}/config/provisioning/datasources/ansible-nas.yml"

- name: Copy Ansible-NAS Dashboard Provisioner
  copy:
    src: grafana/provisioning/dashboards/ansible-nas.yml
    dest: "{{ grafana_data_directory }}/config/provisioning/dashboards/ansible-nas.yml"

- name: Copy Ansible-NAS Dashboard
  copy:
    src: grafana/dashboards/ansible-nas/ansible-nas-overview.json
    dest: "{{ grafana_data_directory }}/data/dashboards/ansible-nas/ansible-nas-overview.json"

- name: Grafana
  docker_container:
    name: grafana
    image: grafana/grafana
    purge_networks: true
    networks:
      - name: stats
      - name: web
    env:
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s"
      GF_SERVER_DOMAIN: "{{ ('grafana.' + ansible_nas_domain) if (grafana_available_externally | bool) or omit }}"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SMTP_ENABLED: "{{ (smtp_host != '') | string }}"
      GF_SMTP_HOST: "{{ smtp_host }}:{{ smtp_port }}"
      GF_SMTP_USER: "{{ smtp_username }}"
      GF_SMTP_PASSWORD: "{{ smtp_password }}"
      GF_SMTP_FROM_ADDRESS: "{{ smtp_sender }}"
      GF_RENDERING_SERVER_URL: http://grafana-image-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
    pull: true
    volumes:
      - "{{ grafana_data_directory }}/data:/var/lib/grafana:rw"
      - "{{ grafana_data_directory }}/config/provisioning:/etc/grafana/provisioning:ro"
    ports:
      - "{{ grafana_port }}:3000"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ grafana_available_externally }}"
      traefik.http.services.grafana-svc.loadbalancer.server.port: "3000"
      traefik.http.routers.grafana.rule: "Host(`grafana.{{ ansible_nas_domain }}`)"
      traefik.http.routers.grafana.tls: "true"

- name: Grafana Image Renderer
  docker_container:
    name: grafana-image-renderer
    image: grafana/grafana-image-renderer:latest
    purge_networks: true
    networks:
      - name: stats
    pull: true
    restart_policy: unless-stopped
    memory: 512m