- name: Create Tautulli Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ tautulli_config_directory }}"
    - "{{ plex_logs }}"

- name: Tautulli Docker Container
  docker_container:
    name: tautulli
    image: linuxserver/tautulli
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ tautulli_config_directory }}:/config:rw"
      - "{{ plex_logs }}:/logs:ro"
    ports:
      - "{{ tautulli_port }}:8181"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ tautulli_user_id }}"
      PGID: "{{ tautulli_group_id }}"
    restart_policy: always
    memory: 1g
    labels:
      traefik.enable: "{{ tautulli_available_externally }}"
      traefik.http.services.tautulli-svc.loadbalancer.server.port: "8181"
      traefik.http.routers.tautulli.rule: "Host(`tautulli.{{ ansible_nas_domain }}`)"
      traefik.http.routers.tautulli.tls: "true"
