---
- name: Create Ubooquity Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ubooquity_data_directory }}"

- name: Ubooquity Docker Container
  docker_container:
    name: ubooquity
    image: linuxserver/ubooquity:latest
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ ubooquity_data_directory }}/config:/config:rw"
      - "{{ ubooquity_data_directory }}/files:/files:rw"
      - "{{ comics_root }}:/comics"
      - "{{ books_root }}:/books"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ ubooquity_user_id|quote }}"
      PGID: "{{ ubooquity_group_id|quote }}"
      MAXMEM: "1024"
    ports:
      - "{{ ubooquity_port_webui }}:2202"
      - "{{ ubooquity_port_admin }}:2203"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ ubooquity_available_externally }}"
      traefik.http.services.ubooquity-svc.loadbalancer.server.port: "2202"
      traefik.http.routers.ubooquity.rule: "Host(`ubooquity.{{ ansible_nas_domain }}`)"
      traefik.http.routers.ubooquity.middlewares: "ubooquity-replacepathregex{% if ldap_enabled|default(false)|bool %},auth-sso{% endif %}"
      traefik.http.routers.ubooquity.tls: "true"
      traefik.http.middlewares.ubooquity-replacepathregex.replacepathregex.regex: "^/(.*)"
      traefik.http.middlewares.ubooquity-replacepathregex.replacepathregex.replacement: "/ubooquity/$1"