---
- name: Create uTorrent Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ utorrent_config_directory }}"
    - "{{ utorrent_download_directory }}"

- name: uTorrent Docker Container
  docker_container:
    name: utorrent
    image: ekho/utorrent:latest
    pull: true
    purge_networks: true
    networks:
      - name: web
    volumes:
      - "{{ utorrent_download_directory }}:/data:rw"
      - "{{ utorrent_config_directory }}:/utorrent/settings:rw"
      - "{{ torrents_root }}:/utorrent/torrents:rw"
    ports:
      - "{{ utorrent_port_http }}:8080"
      - "{{ utorrent_port_bt }}:6881"
      - "{{ utorrent_port_bt }}:6881/udp"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      UID: "{{ utorrent_user_id }}"
      GID: "{{ utorrent_group_id }}"
      webui: "ng"
      dir_active: "/data/.incomplete"
      dir_completed: "/data"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ utorrent_available_externally }}"
      traefik.http.services.utorrent-svc.loadbalancer.server.port: "8080"
      traefik.http.routers.utorrent.rule: "Host(`utorrent.{{ ansible_nas_domain }}`)"
      traefik.http.routers.utorrent.tls: "true"