---
- name: Create Docker Mosquitto network
  docker_network:
    name: mosquitto

- name: Zigbee2MQTT Docker Container
  docker_container:
    name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    pull: true
    purge_networks: true
    restart_policy: always
    networks:
      - name: web
      - name: mosquitto
    devices:
      - "{{ zigbee2mqtt_device }}"
    volumes:
      - "{{ zigbee2mqtt_data_directory }}:/app/data"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    memory: 1g
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      traefik.enable: "{{ zigbee2mqtt_assistant_available_externally }}"
      traefik.http.services.zigbee2mqtt-svc.loadbalancer.server.port: "8080"
      traefik.http.routers.zigbee2mqtt.rule: "Host(`z2m.{{ ansible_nas_domain }}`)"
      traefik.http.routers.zigbee2mqtt.middlewares: "{% if ldap_enabled|default(false)|bool %}auth-sso{% endif %}"
      traefik.http.routers.zigbee2mqtt.tls: "true"