---
- name: Create ZNC Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ znc_data_directory }}"

- name: ZNC
  docker_container:
    name: znc
    image: znc
    purge_networks: true
    networks:
      - name: web
    pull: true
    volumes:
      - "{{ znc_data_directory }}:/znc-data:rw"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "{{ znc_port }}:6677"
    env:
      PUID: "{{ znc_user_id }}"
      PGID: "{{ znc_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ znc_available_externally }}"
      traefik.http.services.znc-svc.loadbalancer.server.port: "6677"
      traefik.http.routers.znc.rule: "Host(`znc.{{ ansible_nas_domain }}`)"
      traefik.http.routers.znc.tls: "true"